### ISSUE TITLE
SILK Life™ YouTube Glitch

### ISSUE THREAD

**Issue by Remy-Reveltek** [WorldEnterpriseGroup/silkcorp#106]
There are some glitches with the five buttons present below the YouTube thumbnail on the SILK Life™ Media Channel. These buttons allow users to select the type of video they want to see from the Yoga, Arts, Cafe, Home, and Tech categories. However, the buttons are facing glitches and are not working correctly.

When users click on one of the buttons, the corresponding playlist is not displayed, and the videos are not playing correctly. This issue is affecting the user experience to view specific video categories.

To resolve this issue, the developers need to investigate the cause of the glitches and fix the code responsible for the buttons' functionality. This could involve debugging the code, checking for errors, and updating the code to ensure that the buttons work correctly.

![image](https://user-images.githubusercontent.com/117187551/228818630-25f881fd-85ed-4d10-86fd-8215c828c079.png)

# Link: https://silkcorp.org/

**Comment by Remy-Reveltek** [comment]
I met with Felix about this issue, and he will work on it once he finishes his ongoing task. During the call, I walked him through the area of the website where we are facing these glitches.

**Comment by Angelus123** [comment]
Remy, I am done with my task we can now hop on a call anytime and work on it.
