### ISSUE TITLE
Update Our Team 3rd Image

### ISSUE THREAD

**Issue by Remy-Reveltek** [WorldEnterpriseGroup/silkcorp#111]
The previous image of a plus-size woman does not align with our core values of strength, integrity, love, and knowledge. Therefore, we need to replace it with an image that reflects SILK's values. The new image should have a matte tone and feature a healthy individual.

![image](https://user-images.githubusercontent.com/117187551/229118663-662f807e-5bee-4b6a-a000-1cdfa7f5fee1.png)

**Comment by Aini-Bashir** [comment]
@Remy-Reveltek, I don't have access to create a branch in it.

**Comment by Aini-Bashir** [comment]
I'm working on this issue.

**Comment by Aini-Bashir** [comment]
@Remy-Reveltek, I did a PR on this issue.
