### ISSUE TITLE
Update Our Team 2nd Image 

### ISSUE THREAD

**Issue by Remy-Reveltek** [WorldEnterpriseGroup/silkcorp#112]
The current image does not align with SILK's core values of strength, integrity, love, and knowledge. We need to update the image to reflect SILK's culture fit. The new image should have a matte tone and showcase a person that aligns with SILK's values.
![image](https://user-images.githubusercontent.com/117187551/229120818-d6fe0d89-ec2c-47c6-842b-76b406e937bb.png)

**Comment by Aini-Bashir** [comment]
I'm working on this issue now.
