### ISSUE TITLE
Replace the dummy content under "SILK SWAG" with relevant content.

### ISSUE THREAD

**Issue by UmerManager** [WorldEnterpriseGroup/silkcorp#22]
Website Link: https://silkcorp.org/
Readme.md file Link: https://github.com/NoteHive/Silk-Corp-Guide

**Follow these Instructions:**
- Content should be defining what SILK SWAG is.  
- Always consider perfect character count.
- Always use uppercase letter when you are starting your Paragraph or even a single word.

Attached image shows what section needs to be worked on
![image](https://user-images.githubusercontent.com/111144473/206183929-9afbab1f-4cc0-43ea-9b45-b741b9c61da4.png)

**Comment by Ftkhan717** [comment]
Someone already worked on this issue, it's merged.

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
