### ISSUE TITLE
Change all 6 titles and content under SILK SWAG with authentic description relating to SILK SWAG 

### ISSUE THREAD

**Issue by UmerManager** [WorldEnterpriseGroup/silkcorp#23]
Website Link: https://silkcorp.org/

**Follow these Instructions: **

- Titles should be defining what SILK SWAG is.
- The definition of titles should be precise and to the point.
- Always consider perfect character count.
- Always use uppercase letters when you are starting your Paragraph or even a single word.
The attached image shows what section needs to be worked on
![image](https://user-images.githubusercontent.com/111144473/206187427-61afec64-8d99-4570-b68f-737a2bbe560b.png)

**Comment by Ftkhan717** [comment]
Somebody already worked on it, It is merged.

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, work on their descriptions
![image](https://user-images.githubusercontent.com/117187551/228903858-ea2d1dc6-edf6-4135-99fc-5c35ee7cec5b.png)

**Comment by bjornmage** [comment]
The content needs updated. Titles are fine, but not the content.

**Comment by Aini-Bashir** [comment]
Alright. I'll work on this issue.

**Comment by Remy-Reveltek** [comment]
Hello everyone starting my work on it.
