### ISSUE TITLE
Update the Address section by adding address, email address, and phone numbers in footer 

### ISSUE THREAD

**Issue by UmerManager** [WorldEnterpriseGroup/silkcorp#27]
@yennefer-m  you can work on this issue:

Website Link: https://silkcorp.org/

**Follow these Instructions:**

- Add authentic address of organization
- Add active email address
- Add two active contact numbers

Please review the image to review the section.
![image](https://user-images.githubusercontent.com/111144473/206202234-1d34e87a-ee28-421d-8da6-fc8313342409.png)

**Comment by Aleem-Reveltek** [comment]
Someone is already worked on it 
![image](https://user-images.githubusercontent.com/117277515/228591875-045e9b10-9a7c-43e4-bdf7-9f137929729d.png)

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
