### ISSUE TITLE
Update the content of footer of website 

### ISSUE THREAD

**Issue by UmerManager** [WorldEnterpriseGroup/silkcorp#30]
Website Link: https://silkcorp.org/

**Follow these Instructions:** 
Update the address.
Update the email address
Update the contact number

You can review the image for reference of exact section:
![image](https://user-images.githubusercontent.com/111144473/206219174-5b2f910a-aecd-4bb6-b96e-f13c5335286f.png)

**Comment by Zaryabayub** [comment]
I am not able to assign it to myself. The "Assignees" won't be clicked upon.

**Comment by UmerManager** [comment]
I have assigned it to you.

**Comment by UmerManager** [comment]
I don't think you have this information. Why you want to work on it?

**Comment by Zaryabayub** [comment]
I was about to ask for the info.

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.

**Comment by Remy-Reveltek** [comment]
@SuzyQuant, can you help us with the right address and phone no.?

**Comment by Aleem-Reveltek** [comment]
Please close this issue someone already worked on it.

![image](https://user-images.githubusercontent.com/117277515/229110873-3a3bef93-4864-4cef-9fb6-c6dc72d3ab32.png)
