### ISSUE TITLE
Change the dummy mockup image of CEO's message

### ISSUE THREAD

**Issue by UmerManager** [WorldEnterpriseGroup/silkcorp#36]
Website Link: https://silkcorp.org/

**Follow these instructions:**

- Change the mockup image with CEO's message.
- 
- Replace the mockup image beside content

Please find the image for reference.
![image](https://user-images.githubusercontent.com/111144473/206418265-fed77574-0280-4c7d-84c7-70f2c5941851.png)

**Comment by Aini-Bashir** [comment]
I'm going to work on this issue.
