### ISSUE TITLE
Change the images of team member and content mentioned with images

### ISSUE THREAD

**Issue by UmerManager** [WorldEnterpriseGroup/silkcorp#37]
Website Link: https://silkcorp.org/

**Please Follow these Instructions:**

- Change all 4 images of team members 
- Make an image having a message from Team member
- Change the image beside the message.

Find the attached image for reference.

![image](https://user-images.githubusercontent.com/111144473/206422500-3234a825-038a-4562-89ec-b6d495e80fd6.png)

**Comment by bjornmage** [comment]
I will research the proper process for changing the photos and have my research finished by the end of today by using Pixlr. I will watch the company training video of how Pixlr functions and follow our procedures for it.

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
All images are updated.
