### ISSUE TITLE
Change the dummy content beside this image.

### ISSUE THREAD

**Issue by Aini-Bashir** [WorldEnterpriseGroup/silkcorp#44]
![Screenshot 2023-02-22 195954](https://user-images.githubusercontent.com/117284277/220661628-e9b30603-b10d-4892-bf0b-e387b185a96e.png)

Hello everyone. 
We are thrilled to announce that our SILK website is nearing completion, and we are currently in the process of updating its images and content to align with our core values and mission. SILK represents Strength, Intelligence, Love, and Kindness, and embodies our commitment to mental, physical, and spiritual wellness, perception and management, caring and hospitality, and community sharing and philanthropy.
SILK is an energy that fosters collective growth and enables individuals to achieve their best potential. We encourage you to consider our values and mission while creating content for our website, which reflects our vibrant culture and community. 
- Write a quote, feedback, or anything suitable for our website. Your choice of content must reflect SILK's actions, core values, and current mission.

Thank you for your support in advancing our mission to empower individuals and communities through Strength, Intelligence, Love, and Kindness.

**Comment by Remy-Reveltek** [comment]
Don't say anything, provide enough info and description for the issues. For example, update the dummy text that should reflect (add a context about your company vision).

**Comment by Remy-Reveltek** [comment]
You can use a template like this for issues "updating dummy text":
# Issue Template 
Hello GitHub People,
We're in the process of completing the SILK Corp website, and we've noticed that the dummy text on the homepage needs to be updated. Could someone please update the text to reflect our current mission and values?
Here are the specifications for the new content/image:
- Follow Character Counts: 184
- Content: (Write a description for your text for example the text should reflect our mission of providing a peaceful community of people while empowering their mental, physical, and emotional well-being. Please update a text that matches our values.)
 
Thanks for your help!

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
