### ISSUE TITLE
Replace images under the #SILKLIFE

### ISSUE THREAD

**Issue by Aini-Bashir** [WorldEnterpriseGroup/silkcorp#45]
![image](https://user-images.githubusercontent.com/117284277/220669308-ca1f200a-442f-4fbb-96cc-f0826b8c299c.png)

Hello everyone. 

SILK Life encompasses a range of activities that align with our SILK website's values and mission to empower people through cooperation, culture, and social interaction. Choose the images that add a clear vision of the services and activities we offer. The new images should showcase our services and events, and represent the core values of Strength, Intelligence, Love, and Kindness. 

Here are the specifications for the new images:
- File format: JPEG or PNG
- Right-click on the image, check "Inspects" to know the dimension (length and width) of the image, and choose a new image according to that dimension.

Thank you.

**Comment by Remy-Reveltek** [comment]
You can use a template like this for your issues:
# Issue Template 
Hello GitHub People,
We're in the process of completing the SILK Corp website, and we've noticed that the image on the homepage needs to be updated. Could someone please update the image to reflect our current mission and values?
Here are the specifications for the new content/image:
- Dimensions: 1200px x 800px
- File format: JPEG or PNG
- Content: (Write a description for your image for example the image should reflect our mission of providing a peaceful community of people while empowering their mental, physical, and emotional well-being. Please choose an image that is visually appealing and relevant to our brand.)
 
Thanks for your help!

**Comment by Remy-Reveltek** [comment]
Provide enough info so issues make more sense to everyone.

**Comment by Aini-Bashir** [comment]
I've updated this issue.

**Comment by duafatimaa** [comment]
@Remy-Reveltek, I am going to work on adding an image in the Art section of #SILKLIFE.

**Comment by Aini-Bashir** [comment]
@duafatimaa Can we hop on a call for 10 minutes?

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
