### ISSUE TITLE
Replace images beside the SILK mission

### ISSUE THREAD

**Issue by Aini-Bashir** [WorldEnterpriseGroup/silkcorp#46]
![image](https://user-images.githubusercontent.com/117284277/220696245-ae6e3901-c883-4731-a487-8872673082ec.png)

Hello everyone.

We would like to request an update to the image beside our SILK mission statement on our website. SILK spaces are holistic and driven by the passion of its people in everything we do. The energy of the SILK Team is to attract like-minded people.
To better reflect our core values and mission, we would like to replace the existing image with a new one that truly embodies what SILK is all about. 
- Rendered size: 720 × 492 px
- File size: 626 kB

Thank you.

**Comment by Aini-Bashir** [comment]
Updated this issue.

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
