### ISSUE TITLE
Replace images for the SILK SWAG

### ISSUE THREAD

**Issue by Aini-Bashir** [WorldEnterpriseGroup/silkcorp#47]
![Screenshot 2023-02-22 215558](https://user-images.githubusercontent.com/117284277/220700790-e8db159e-0d43-45a9-87b3-956e0f8cf06a.png)

Hello everyone. 

SILK SWAG also encompasses our SILK Y.A.C.H.T activities. To better reflect our core values and mission, we would like to replace the existing image with a new one that truly embodies what SILK is all about. please ensure that the image is high-quality, relevant, and in line with our website. We appreciate your input and collaboration in selecting the perfect image for our SILK SWAG section.
 
# Inspects: 
- Rendered size:	720 × 696 px
- File size:	302 kB
- Current source: https://silkcorp.org/img/mock-up-2.png

**Comment by Remy-Reveltek** [comment]
Provide more context and read comments on your other issues.

**Comment by Aini-Bashir** [comment]
Okay. I read all the comments and working on it.

**Comment by Aini-Bashir** [comment]
Can I create a new file in the gh-pages of the SILK repo for the .md file?

**Comment by Remy-Reveltek** [comment]
Also, add:
"Use non-copywrite image"

**Comment by bjornmage** [comment]
![image](https://user-images.githubusercontent.com/4495532/228612431-ee4cdf04-8081-4494-b724-6496c17c16d8.png)

Here's a start for it. 

Go into Envato Elements and get all the recent downloads that I got from there on behalf of SILK Corp. 
Then, manipulate those and save all the non-destructive layers. Then, make a collage for this particular area.

Research what "non-destructive layers" means and make sure you do this step in Photoshop.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, go inside this issue description and change the size in description to 1200 x 1160

**Comment by Remy-Reveltek** [comment]
@Aleem-Reveltek, you will be working on it.

**Comment by Aleem-Reveltek** [comment]
Okay, I'm going to start working on this task.

**Comment by Remy-Reveltek** [comment]
@Aleem-Reveltek, I understand that you are working on design inside Photoshop but communicate inside throughout the day. As your team will get to know that you are working on it and started your work for the day.

**Comment by Aleem-Reveltek** [comment]
![Screenshot 2023-03-31 221041](https://user-images.githubusercontent.com/117277515/229185948-096859b7-2123-4fc7-8145-81b6d588db82.png)

**Comment by Aleem-Reveltek** [comment]
I have done this work till now.

**Comment by Aleem-Reveltek** [comment]
@bjornmage, the mockup I'm going to make I'm going to put only three product that you have given above?

**Comment by bjornmage** [comment]
Whatever you want. Just make it look cool.

**Comment by Aleem-Reveltek** [comment]
Okay, thank you so much.

**Comment by Aleem-Reveltek** [comment]
@bjornmage, The brand name will be SILK Corp or any other suggestion you have?

**Comment by Aleem-Reveltek** [comment]
![image](https://user-images.githubusercontent.com/117277515/229203766-f0b4de3c-e317-43ba-a5b3-1db55aa8b44f.png)

**Comment by Aleem-Reveltek** [comment]
![image](https://user-images.githubusercontent.com/117277515/229205665-5fd7c4f0-82ce-4897-b764-eccdd01a7428.png)

**Comment by Aleem-Reveltek** [comment]
![image](https://user-images.githubusercontent.com/117277515/229210384-9efba7c2-2ffa-4d8a-9395-c607e000d745.png)

**Comment by Aleem-Reveltek** [comment]
![image](https://user-images.githubusercontent.com/117277515/229213316-4496d144-b647-49c6-977e-7dd07286dee4.png)

**Comment by Aleem-Reveltek** [comment]
I'm done with this issue this issue is merged.

![image](https://user-images.githubusercontent.com/117277515/229498323-6fffc968-4c65-46aa-9e6a-d8afae7f2fd2.png)
