### ISSUE TITLE
Images required for SILK Life.

### ISSUE THREAD

**Issue by Aini-Bashir** [WorldEnterpriseGroup/silkcorp#50]
# Website:  [SILK Corp](https://silkcorp.org/)

![image](https://user-images.githubusercontent.com/117284277/221255490-12dc11af-f84e-4dbd-9ba0-f92c98aebf51.png)

Hello everyone.
- As part of our ongoing efforts to expand the reach and impact of SILK, we have an area of media channel dedicated to promoting our core values
of Strength, Intelligence, Love, and Kindness. 
- This area could take the form of a blog, article, or video series, and would provide a platform for us to share our ideas, insights, and experiences with a wider audience.
- Images should be high-quality, relevant, and in line with our core values, be visually appealing, and help to convey the message of the content.
- Also, change the logo.png behind the content relevant to the SILK media. 
- Rendered size: 400 × 800 px
- File size: 255 kB
- Current source: https://silkcorp.org/img/mock-up-1.png

**Comment by Remy-Reveltek** [comment]
Work on this Issue Fajar
@Ftkhan717@gmail.com

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
Now we have a new #106 issue for it.
