### ISSUE TITLE
Images for our Team 

### ISSUE THREAD

**Issue by Aini-Bashir** [WorldEnterpriseGroup/silkcorp#51]
# Website:  [SILK Corp](https://silkcorp.org/)

 ![image](https://user-images.githubusercontent.com/117284277/221256504-c7dca85b-2a3f-4456-a898-ed1fb2241e1d.png)

Hello team,

We aim to represent our team in a professional and polished manner to ensure that our website visitors have a positive impression of our organization.
To achieve this, we request that the current images of team members be replaced with professional headshots to better represents our company. Also, change the dummy content behind each member to represent their roles in the organization.

### Inspects
- Rendered size: 345 × 345 px
- Format: JPEG or PNG

**Comment by Aini-Bashir** [comment]
@Remy-Reveltek, there is dummy content behind the images of "Our team" that needs to be updated.

**Comment by Aini-Bashir** [comment]
At the very last of the web, textual content for the whole "Contact" area needs to be updated.

**Comment by Aini-Bashir** [comment]
![image](https://user-images.githubusercontent.com/117284277/225012903-cd178882-37bd-4204-b906-23ebfd56fbeb.png)
 
This area also needs to be updated.

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
