### ISSUE TITLE
Replace images for the SILK YACHT.

### ISSUE THREAD

**Issue by Aini-Bashir** [WorldEnterpriseGroup/silkcorp#52]
# Website:  [SILK Corp](https://silkcorp.org/)

![image](https://user-images.githubusercontent.com/117284277/221556975-f05ec333-3340-44b1-84ee-f6240ba71380.png)
Hello everyone

We are thrilled to announce that our SILK website is nearing completion, and we are currently in the process of updating its images and content to align with our core values and mission. SILK represents Strength, Intelligence, Love, and Kindness, and embodies our commitment to mental, physical, and spiritual wellness, perception and management, caring and hospitality, and community sharing and philanthropy.

Our website features Y.A.C.H.T activities that cater to diverse interests and objectives.

- Y focuses on empowering individuals with mental and physical strength through yoga and meditation practices.
- A centers around the arts and encompasses a range of creative activities such as dance, music, craft, brainstorming, and creativity.
- C represents our cafe, which emphasizes healthy recipes, cooking techniques, hygiene, organization, and sanitation.
- H represents our hive, which emphasizes socialization, collaboration, community-building, and cultural sharing.
- T represents our tech activities, which aim to empower individuals with knowledge of cutting-edge technologies and artificial intelligence, enabling them to take productive actions and achieve their goals.
SILK is an energy that fosters collective growth and enables individuals to achieve their best potential. We encourage you to consider our values and mission while creating content for our website, which reflects our vibrant culture and community.

Please select images that effectively convey our SILK Y.A.C.H.T activities for our website while also ensuring that the images conform to the specifications required for our website's layout. It is important to carefully consider the size, resolution, and aspect ratio of the images to ensure they do not disrupt the overall design and usability of our website.

Thank you.

**Comment by Remy-Reveltek** [comment]
@rbutt0758@gamil.com

**Comment by Remy-Reveltek** [comment]
@Ftkhan717@gmail.com, work on this issue.

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
