### ISSUE TITLE
S.I.L.K. icons

### ISSUE THREAD

**Issue by Aini-Bashir** [WorldEnterpriseGroup/silkcorp#56]
![image](https://user-images.githubusercontent.com/117284277/223129452-e5bc87b5-de4b-4f0e-8df3-5714d8ec6d68.png)

Website: [SILK Corp](https://silkcorp.org/)
Hello everyone.
We are in the process of completing our SILK website, and we are currently updating its images, logos, icons, and content to align with our core values and mission. For more detail about our SILK website, visit this link [(SILK)](https://github.com/WorldEnterpriseGroup/silkcorp/blob/gh-pages/Issues.md) to get more information on it. 
Please replace these little icons as shown in the above image that reflects our S.I.L.K. Consider their dimensions and perfect pixels to not distort the image. 

Thank you.

**Comment by Remy-Reveltek** [comment]
**Request to Close**
This issue is solved, please close it.
