### ISSUE TITLE
YouTube Videos Playlist Slider for SILK Life™ Media Channel

### ISSUE THREAD

**Issue by Remy-Reveltek** [WorldEnterpriseGroup/silkcorp#96]
# Description
In SILK Life™ Media Channel, we want to create a slider that displays YouTube video playlists related to different categories such as Yoga, Arts, Cafe, Home, and Tech. The slider should be interactive and allow the user to select a particular category and display the corresponding playlist. The slider should also adjust the size of the playlists based on the user's selection, making the selected playlist larger and the others smaller.

## Instructions
- Clone this repository to your local machine
- Navigate to the cloned repository folder
- Open the index.html file in a web browser

## Technologies Used
- HTML
- CSS
- JavaScript
- YouTube API

![image](https://user-images.githubusercontent.com/117187551/226012820-05fd5e36-1033-4175-9d36-a9460d0842e2.png)

# https://silkcorp.org/

**Comment by bjornmage** [comment]
https://github.com/Giorgio003/Youtube-TV

http://giorgio003.github.io/Youtube-TV/demos/responsive.html

I believe we should consider the following JS code as it supports playlists well.

**Comment by Remy-Reveltek** [comment]
@Aleem-Reveltek, once you start working on this issue comment here on your approach.

**Comment by Aleem-Reveltek** [comment]
I'm going to start working on this project and I'll let you know guys the updates which I'm going to make in Figma.

**Comment by bjornmage** [comment]
![image](https://user-images.githubusercontent.com/4495532/228606677-fe9dfa5e-3a37-483a-b700-863d4e9d8916.png)

I just made a commit on this.  Commit 87c7b04e069608fbff81d1a9c96fa2f26bca7a9b

As  you can see, it's not perfect, but it sort of works.  Let's get Felix on this to clean it up more or switch over to the previous version that I mentioned here:
https://github.com/Giorgio003/Youtube-TV
http://giorgio003.github.io/Youtube-TV/demos/responsive.html

**Comment by Aleem-Reveltek** [comment]
You guys mean making this kind of low-fi design
![image](https://user-images.githubusercontent.com/117277515/228608310-a333c51b-dc0b-47da-b90a-b838aa4f4428.png)

**Comment by Remy-Reveltek** [comment]
@Aleem-Reveltek, let's stop working on it. We have made some changes in this section once it will update on the website. I will assign it Felix to work on this section to clean up some glitches we may face.

**Comment by Aleem-Reveltek** [comment]
@Remy-Reveltek  I didn't read your comment but I worked on it https://www.figma.com/file/LMjwC2r2BnRwOZJbZbEaCe/SILK-Corp?node-id=0%3A1&t=lS0uwpzxCVR35zky-1

**Comment by Aleem-Reveltek** [comment]
[Figma file](https://www.figma.com/file/LMjwC2r2BnRwOZJbZbEaCe/SILK-Corp?node-id=0%3A1&t=lS0uwpzxCVR35zky-1)
